### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by krumberg**
Added cmake support and missing include

### CODE REVIEW

**Comment by Dwii** [comment]
I had to add `set (CMAKE_C_FLAGS "--std=gnu99 ${CMAKE_C_FLAGS}")` in CMakeLists.txt and put all headers of `Dropbox/include` in the `Dropbox/src` to make it work. I never used cmake until now, so did I missed something ?

**Comment by krumberg** [comment]
Sorry! You are correct! I'm compiling dropbox-c as a component in a larger cmake based project where I have already added the include path and enabled c99 on a high level.

**Comment by krumberg** [comment]
Sorry for the massive delay, I have now updated my patch.

**Comment by Dwii** [comment]
Thanks for this patch Krumberg. 

For the record, I had an issue with the way c99 is handled (e.i. `SET_PROPERTY(TARGET dropboxc PROPERTY C_STANDARD 99)`) on my "old" Ubuntu and Mint VM (flag was not added and I could not compile). However, it seems to be the right way to handle this and it work fine on a fresh Ubuntu 16.04 and on Mac OSX 10.10.5.

About Mac OSX, I still had to add `INCLUDE_DIRECTORIES("/usr/local/include")` to make it work. I'll commit this change myself later.

**Comment by krumberg** [comment]
Thanks you for creating such a great project!

I guess that the property C_STANDARD is not supported in older versions of CMake. I use cmake from brew and I don't need to add this include path.

**Pull request merged**
